version: '3.9'


x-base_service: &base_service
  stop_signal: SIGKILL

  ports:
    - "8000:8000"
    - "8001:8001"
    - "8002:8002"

  volumes:
    - &v_base .:/workspace
    - &v_models ./models:/models
    - &v_data ./data:/data

    # debug
    - &v_export ./export:/workspace
    - &v_triton ./triton:/workspace
    - &v_client ./client:/workspace
  tty: true

name: wav2vec2

services:
  export: 
    <<: *base_service
    build: ./export
    profiles: ['export','all']
    volumes:
      - *v_models
      - *v_data
  
  triton-server:
    <<: *base_service
    build: ./triton
    profiles: ['triton','all']
    volumes:
      - *v_models
    # command: 'tritonserver --model-repository /models --log-verbose 1' # debug


  triton-client:
    <<: *base_service
    build: ./client
    profiles: ['client','all']
    volumes:
      - *v_data
    # command: 'tritonserver --model-repository /models --log-verbose 1' # debug
