version: '3.9'

name: wav2vec2-triton


x-base_service: &base
  stop_signal: SIGKILL
  tty: true
  volumes:
    - &v_models ./models:/models
    - &v_data ./data:/data

    # debug
    - &v_workspace .:/workspace
    - &v_export ./export:/workspace
    - &v_triton ./triton:/workspace
    - &v_client ./client:/workspace
    - &v_models_fp16 ./models_fp16:/models


services:
  export: 
    <<: *base
    build: ./export
    profiles: ['export','all']
    volumes:
      - *v_models
      - *v_data
      - *v_export

  
  server:
    <<: *base
    build: ./triton
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

    profiles: ['server','all']
    volumes:
      # - *v_models
      - *v_models_fp16

    # command: 'tritonserver --model-repository /models --log-verbose 1' # debug


  client:
    <<: *base
    build: ./client
    profiles: ['client','all']
    volumes:
      - *v_data
      - *v_client
